"""ODIN Forms - parse and render declarative form definitions."""

from .accessibility import (
    contrast_ratio,
    field_aria_attrs,
    field_group_html,
    field_label_html,
    generate_field_id,
    meets_contrast_aa,
    skip_link_html,
    sr_only_html,
    tab_order_sort,
)
from .css import generate_form_css, generate_print_css
from .parser import parse_form
from .renderer import render_form
from .types import (
    BarcodeElement,
    BaseElement,
    BaseFieldElement,
    CheckboxElement,
    CircleElement,
    DateElement,
    EllipseElement,
    FormElement,
    FormFieldElement,
    FormMetadata,
    FormPage,
    ImageElement,
    LineElement,
    MultiselectElement,
    OdinForm,
    PageDefaults,
    PageMargins,
    PageTemplate,
    PathElement,
    PolygonElement,
    PolylineElement,
    RadioElement,
    RectElement,
    RegionElement,
    RenderFormOptions,
    ScreenSettings,
    SelectElement,
    SignatureElement,
    TextElement,
    TextFieldElement,
)
from .units import from_pixels, to_pixels

__all__ = [
    "parse_form",
    "render_form",
    "generate_form_css",
    "generate_print_css",
    "to_pixels",
    "from_pixels",
    "generate_field_id",
    "field_label_html",
    "field_aria_attrs",
    "field_group_html",
    "tab_order_sort",
    "skip_link_html",
    "sr_only_html",
    "contrast_ratio",
    "meets_contrast_aa",
    "OdinForm",
    "FormMetadata",
    "PageDefaults",
    "PageMargins",
    "ScreenSettings",
    "FormPage",
    "BaseElement",
    "BaseFieldElement",
    "LineElement",
    "RectElement",
    "CircleElement",
    "EllipseElement",
    "PolygonElement",
    "PolylineElement",
    "PathElement",
    "TextElement",
    "ImageElement",
    "BarcodeElement",
    "TextFieldElement",
    "CheckboxElement",
    "RadioElement",
    "SelectElement",
    "MultiselectElement",
    "DateElement",
    "SignatureElement",
    "RegionElement",
    "PageTemplate",
    "FormElement",
    "FormFieldElement",
    "RenderFormOptions",
]
